; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-evb]
platform = espressif32
board = esp32-evb
framework = arduino
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson@^7.0.4
	adafruit/RTClib@^2.1.3
	arduino-libraries/NTPClient@^3.2.1
	marian-craciunescu/ESP32Ping@^1.7
	tobiasschuerg/ESP8266 Influxdb@^3.13.1
	ayushsharma82/ElegantOTA@^3.1.7
	esp32async/ESPAsyncWebServer@^3.9.6
	esp32async/AsyncTCP@^3.4.10
	marvinroger/AsyncMqttClient@^0.9.0
lib_extra_dirs = lib/esp-utils
platform_packages = 
	tool-esptoolpy @ 1.40501.0

[env:Production]
board = sparkfun_esp32_iot_redboard

[env:Dev]
board = esp32-evb
lib_deps =
	bblanchon/ArduinoJson@^7.0.4
	adafruit/RTClib@^2.1.3
	arduino-libraries/NTPClient@^3.2.1
	marian-craciunescu/ESP32Ping@^1.7
	tobiasschuerg/ESP8266 Influxdb@^3.13.1
	ayushsharma82/ElegantOTA@^3.1.7
	esp32async/ESPAsyncWebServer@^3.9.6
	esp32async/AsyncTCP@^3.4.10
	marvinroger/AsyncMqttClient@^0.9.0
